---
title: "sparseDOSSA simulation for adjust.batch function"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
sparseDOSSA simulation study for batch adjustment function

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath("../"))
# setwd("simulation/")
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup()
dir_output <- "results/adjust.batch/"
dir.create(dir_output, recursive = TRUE, showWarnings = TRUE)
```

```{r simulation parameters}
# sample size
nBatch <- c(5, 10)
nSample_perBatch <- c(10, 50, 100)
# feature size
nMicrobe <- c(50, 300)
spikeMicrobes <- c(0.1, 0.2, 0.5)
# metadata specification
metadata_type <- c("batch" = "factor",
                   "positive_control" = "numeric",
                   "negative_control" = "numeric")
effectSize <- tibble::tibble(effectSize = 
                               list(c("batch" = 0.1, "positive_control" = 1, "negative_control" = 0),
                                    c("batch" = 1, "positive_control" = 1, "negative_control" = 0),
                                    c("batch" = 10, "positive_control" = 1, "negative_control" = 0)))
# replicates
rep <- 1:10
fDummyData <- FALSE
# additional setup
noZeroInflate <- FALSE

tb_simSetup <- tidyr::crossing(
  rep,
  nBatch,
  nSample_perBatch,
  nMicrobe,
  spikeMicrobes,
  noZeroInflate,
  effectSize
) %>% 
  dplyr::mutate(nSample = nBatch * nSample_perBatch)
```

```{r simulate metadata}
set.seed(1)
tb_sim <- tb_simSetup %>% 
  dplyr::group_by(1:n()) %>% 
  dplyr::mutate(df_metadata = list(
    data.frame(batch = rep(1:nBatch, each = nSample_perBatch) %>% 
                 as.factor(),
               positive_control = rnorm(1:nSample),
               negative_control = rnorm(1:nSample))
  )) %>% 
  dplyr::ungroup()
save(tb_sim, file = paste0(dir_output, "tb_sim.RData"))
```

```{r run sparseDOSSA}
registerDoParallel(15)
l_sparseDOSSA <- foreach(i = 1:nrow(tb_sim)) %dopar% {
  i_simSetup <- tb_sim[i, ]
  
  # Error control using `try`,
  tryAgain <-  TRUE
  infiniteloopcounter <- 1
  while (tryAgain & infiniteloopcounter < 5) {
    otu_count <- try(sparseDOSSA::sparseDOSSA(
      number_features = i_simSetup$nMicrobe,
      number_samples = i_simSetup$nSample,
      UserMetadata = 
        create_metadataMatrix(df_metadata = i_simSetup$df_metadata[[1]],
                              metadata_type = metadata_type,
                              fDummyData = fDummyData),
      Metadatafrozenidx = 
        create_fronzenIndex(df_metadata = i_simSetup$df_metadata[[1]],
                            metadata_type = metadata_type,
                            fDummyData = fDummyData),
      datasetCount = 1,
      spikeStrength =                                                                             
        create_effectSize(effectSize = i_simSetup$effectSize[[1]],
                          df_metadata = i_simSetup$df_metadata[[1]],
                          metadata_type = metadata_type,
                          fDummyData = fDummyData) %>% 
        paste(collapse = ","),
      noZeroInflate = i_simSetup$noZeroInflate,
      percent_spiked = i_simSetup$spikeMicrobes,
      seed = i_simSetup$rep,
      minLevelPercent = 0,
      write_table = FALSE,
      verbose = FALSE) %>%
        extract_sparseDOSSA() %>%
        extract2("features"),
      silent = TRUE)
    if (is.null(otu_count) | inherits(otu_count, "try-error")) {
      tryAgain = TRUE
      infiniteloopcounter = infiniteloopcounter + 1
    } else {
      tryAgain = FALSE
    }
  }
  return(otu_count)
}
stopImplicitCluster()
save(l_sparseDOSSA, file = paste0(dir_output, "sparseDOSSA.RData"))
```
