---
title: "sparseDOSSA simulation for discrete structure discovery"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
sparseDOSSA simulation for discrete structure discovery

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath("../"))
# setwd("simulation/")
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup()
dir_output <- "results/discrete/"
dir.create(dir_output, recursive = TRUE, showWarnings = TRUE)
```

```{r simulation parameters}
# parallel computing
ncores <- 15
# sample size
nBatch <- c(2, 5, 10)
nCluster <- c(4, 8)
nSample_perCluster <- c(20, 100)
# feature size
nMicrobe <- c(200, 1000)
spikeMicrobes <- c(0.2)
# metadata specification
metadata_type <- c("batch" = "factor",
                   "cluster" = "factor")
tb_effectSize <- tidyr::crossing(batch = 0:10,
                                 cluster = c(5, 10))
effectSize <- tibble::tibble(effectSize = 
                               (1:nrow(tb_effectSize)) %>% 
                               purrr::map(function(i) unlist(tb_effectSize[i, ])))
# replicates
rep <- 1:5
# metadata simulation
fDummyData <- TRUE
fDummyDirection <- TRUE
# additional setup
noZeroInflate <- FALSE

tb_simSetup <- tidyr::crossing(
  rep,
  nBatch,
  nCluster,
  nSample_perCluster,
  nMicrobe,
  spikeMicrobes,
  noZeroInflate,
  effectSize
) %>% 
  dplyr::mutate(nSample = nBatch * nCluster * nSample_perCluster)
```

```{r simulate metadata}
set.seed(1)
tb_sim <- tb_simSetup %>% 
  dplyr::group_by(1:n()) %>% 
  dplyr::mutate(df_metadata = list(
    data.frame(batch = sample.int(nBatch, size = nSample, replace = TRUE) %>% 
                 as.factor(),
               cluster = rep(1:nCluster, each = nSample_perCluster*nBatch) %>% 
                 as.factor(),
               row.names = paste0("Sample", 1:nSample))),
    spikein.mt = create_effectSize(effectSize = effectSize[[1]],
                                   df_metadata = df_metadata[[1]],
                                   metadata_type = metadata_type,
                                   fDummyData = fDummyData,
                                   fDummyDirection = fDummyDirection) %>% 
      create_spikein.mt(number_features = nMicrobe,
                        percent_spiked = spikeMicrobes,
                        effectSize = .,
                        seed = rep) %>% 
      list()) %>% 
  dplyr::ungroup()
save(tb_sim, file = paste0(dir_output, "tb_sim.RData"))
N <- nrow(tb_sim)
```

```{r run sparseDOSSA}
registerDoParallel(ncores)
set.seed(1)
# l_sparseDOSSA1 <- foreach(i = 1:N) %dopar% {
#   i_simSetup <- tb_sim[i, ]
#   
#   otu_count <- 1:nCluster %>% 
#     purrr::map(function(i_cluster) 
#       sparseDOSSA::sparseDOSSA(
#         number_features = i_simSetup$nMicrobe,
#         number_samples = i_simSetup$nSample_perCluster * i_simSetup$nBatch,
#         noZeroInflate = i_simSetup$noZeroInflate,
#         percent_spiked = i_simSetup$spikeMicrobes,
#         seed = i_cluster,
#         minLevelPercent = 0,
#         write_table = FALSE,
#         verbose = FALSE) %>%
#         extract_sparseDOSSA() %>%
#         extract2("features")
#     ) %>% 
#     purrr::reduce(cbind)
#   colnames(otu_count) <- paste0("Sample", 1:ncol(otu_count))
#   return(otu_count)
# }
l_sparseDOSSA <- foreach(i = 1:N) %dopar% {
  i_simSetup <- tb_sim[i, ]
  
  otu_count <- sparseDOSSA::sparseDOSSA(
    number_features = i_simSetup$nMicrobe,
    number_samples = i_simSetup$nSample,
    UserMetadata = 
      create_metadataMatrix(df_metadata = i_simSetup$df_metadata[[1]],
                            metadata_type = metadata_type,
                            fDummyData = fDummyData,
                            fDummyDirection = fDummyDirection,
                            scale = FALSE),
    spikein.mt = i_simSetup$spikein.mt[[1]] %>% 
      dplyr::group_by(feature) %>% 
      dplyr::mutate(metadata = paste(metadata, collapse = ";"), 
                    strength = paste(strength, collapse = ";")) %>% 
      dplyr::slice(1) %>%  
      dplyr::ungroup(),
    noZeroInflate = i_simSetup$noZeroInflate,
    percent_spiked = i_simSetup$spikeMicrobes,
    seed = i_simSetup$rep,
    minLevelPercent = 0,
    write_table = FALSE,
    verbose = FALSE) %>%
    extract_sparseDOSSA() %>%
    extract2("features")
  return(otu_count)
}
stopImplicitCluster()
save(l_sparseDOSSA, file = paste0(dir_output, "sparseDOSSA.RData"))
```
