---
title: "summarise discrete structure discovery"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
Summarise discrete structure discovery

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath("../"))
# setwd("simulation/")
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup()
dir_output <- "results/discrete/"
dir.create(dir_output, recursive = TRUE, showWarnings = TRUE)
```

```{r load data}
load(paste0(dir_output, "tb_sim.RData"))
tb_sim <- tb_sim %>% 
  dplyr::mutate(effect_cluster = effectSize %>% 
                  purrr::map_dbl("cluster"),
                effect_batch = effectSize %>% 
                  purrr::map_dbl("batch"),
                i = 1:n()) %>% 
  dplyr::select(-`1:n()`)
load(paste0(dir_output, "evaluate_before.RData"))
load(paste0(dir_output, "evaluate_after.RData"))
```

```{r sanity check}
tb_R2 <- list(results, results_correct) %>% 
  purrr::map2_dfr(names(colors_simulation_unsupervised), 
                  ~ .x %>% 
                    purrr::imap_dfr(~ data.frame(R2_cluster = .x$R2["cluster"],
                                                 R2_batch = .x$R2["batch"],
                                                 i = .y)) %>% 
                    data.frame(Data = .y)) %>% 
  dplyr::mutate(Data = factor(Data, levels = names(colors_simulation_unsupervised)))

ps_R2_batch <- c(200, 1000) %>% 
  purrr::map(function(i_nSample) {
    tb_R2 %>% 
      dplyr::left_join(tb_sim, by = "i") %>% 
      dplyr::filter(nSample == i_nSample) %>%
      dplyr::filter(!(effect_batch == 0 & Data == "MMUPHin corrected")) %>% 
      dplyr::filter(effect_cluster == 10) %>% 
      ggplot(aes(x = as.factor(effect_batch), y = R2_batch, 
                 color = Data)) +
      geom_boxplot() +
      facet_grid(paste0("nBatch=", nBatch)~paste0("nCluster=", nCluster)) +
      ggtitle(paste0("nSample = ", i_nSample)) +
      scale_color_manual(values = colors_simulation_unsupervised)
  })
cowplot::plot_grid(plotlist = ps_R2_batch, nrow = 1) %>% 
  ggsave(filename = paste0(dir_output, "R2_batch.pdf"), ., width = 30, height = 10)
ps_R2_cluster <- c(200, 1000) %>% 
  purrr::map(function(i_nSample) {
    tb_R2 %>% 
      dplyr::left_join(tb_sim, by = "i") %>% 
      dplyr::filter(nSample == i_nSample) %>% 
      dplyr::filter(!(effect_batch == 0 & Data == "MMUPHin corrected")) %>% 
      dplyr::filter(effect_cluster == 10) %>% 
      ggplot(aes(x = as.factor(effect_batch), y = R2_cluster, 
                 color = Data)) +
      geom_boxplot() +
      facet_grid(paste0("nBatch=", nBatch)~paste0("nCluster=", nCluster)) +
      ggtitle(paste0("nSample = ", i_nSample)) +
      scale_color_manual(values = colors_simulation_unsupervised)
  })
cowplot::plot_grid(plotlist = ps_R2_cluster, nrow = 1) %>% 
  ggsave(filename = paste0(dir_output, "R2_cluster.pdf"), ., width = 30, height = 10)
```
```{r how many cases successed in spiking in clustering structure?}
tb_predStr <- list(results, results_correct) %>% 
  purrr::map2_dfr(names(colors_simulation_unsupervised), 
                  ~ .x %>% 
                    purrr::imap_dfr(function(result, i) {
                      nCluster_true <- tb_sim[i, ]$nCluster
                      tb_result <- result$pred.str
                      tb_result %>% 
                        dplyr::arrange(-(k == nCluster_true),
                                       -mean_pred) %>% 
                        dplyr::slice(1:2) %>% 
                        dplyr::arrange(-mean_pred) %>% 
                        dplyr::mutate(pred_str_rank = c("highest", "second"),
                                      i = i)
                    }) %>% 
                    data.frame(Data = .y)) %>% 
  dplyr::mutate(Data = factor(Data, levels = names(colors_simulation_unsupervised)))

ps_success <- c(200, 1000) %>% 
  purrr::map(function(i_nSample) {
    tb_predStr %>% 
      dplyr::filter(pred_str_rank == "highest") %>% 
      dplyr::left_join(tb_sim, by = "i") %>% 
      dplyr::filter(nSample == i_nSample) %>%
      dplyr::filter(!(effect_batch == 0 & Data == "MMUPHin corrected")) %>% 
      dplyr::filter(effect_cluster == 10) %>% 
      dplyr::mutate(success = (k == nCluster)) %>% 
      dplyr::group_by(effect_batch,
                      nCluster, nBatch,
                      nMicrobe, Data) %>% 
      dplyr::summarise(mean_success = mean(success)) %>% 
      ggplot(aes(x = as.factor(effect_batch), y = mean_success, 
                 color = Data)) +
      geom_point(position = position_dodge(width = 0.5), size = 3) +
      facet_grid(paste0("nBatch=", nBatch)~paste0("nCluster=", nCluster)) +
      ggtitle(paste0("nSample = ", i_nSample)) +
      scale_color_manual(values = colors_simulation_unsupervised)
  })
cowplot::plot_grid(plotlist = ps_success, nrow = 1) %>% 
  ggsave(filename = paste0(dir_output, "simulation_result.pdf"), ., width = 30, height = 10)
```


```{r prediction strength comparison}
ps_predStr <- c(200, 1000) %>% 
  purrr::map(function(i_nSample) {
    tb_predStr %>% 
      dplyr::left_join(tb_sim, by = "i") %>% 
      dplyr::filter(nSample == i_nSample) %>% 
      dplyr::filter(!(effect_batch == 0 & Data == "MMUPHin corrected")) %>% 
      dplyr::filter(effect_cluster == 10) %>% 
      dplyr::mutate(k_identified = ifelse(k == nCluster,
                                          "Correct",
                                          "Highest") %>% 
                      factor(levels = c("Highest", "Correct"))) %>% 
      ggplot(aes(x = as.factor(effect_batch), y = mean_pred, 
                 alpha = k_identified, fill = Data)) +
      geom_boxplot() +
      facet_grid(paste0("nBatch=", nBatch)~paste0("nCluster=", nCluster)) +
      ggtitle(paste0("nSample = ", i_nSample)) +
      scale_fill_manual(values = colors_simulation_unsupervised) +
      scale_alpha_manual(values = c("Highest" = 0.5, "Correct" = 1))
  })
cowplot::plot_grid(plotlist = ps_predStr, nrow = 1) %>% 
  ggsave(filename = paste0(dir_output, "prediction_strength.pdf"), ., width = 30, height = 10)
```


```{r find example case}
is <- tb_sim %>% 
  dplyr::filter(nCluster == 3, effect_batch == 10, effect_cluster == 10,
                nBatch == 2, nSample == 1000) %>% 
  extract2("i")
for(i in is) {
  mat_otu <- readr::read_tsv(paste0(dir_output,
                                    "sparseDOSSA_sets/",
                                    i, ".tsv")) %>% 
    as.matrix
  rownames(mat_otu) <- paste0("Feature", 1:nrow(mat_otu))
  i_simSetup <- tb_sim[i, ]
  df_metadata <- tb_sim[i, ]$df_metadata[[1]]
  
  phylo <- phyloseq::phyloseq(
    phyloseq::otu_table(mat_otu, taxa_are_rows = TRUE),
    sample_data(df_metadata)) %>%
    transform_sample_counts(MMUPHin:::tss) %>%
    prune_taxaSamples()
  
  mat_otu_adj <- mat_otu %>% 
      MMUPHin::adjust.batch(batch = "batch", 
                            data = df_metadata,
                            diagnostics = FALSE, 
                            verbose = FALSE)
  phylo_adj <- phyloseq::phyloseq(
    phyloseq::otu_table(mat_otu_adj, taxa_are_rows = TRUE),
    sample_data(df_metadata)) %>%
    transform_sample_counts(MMUPHin:::tss) %>%
    prune_taxaSamples()
  
  l_p <- list(phylo, phylo_adj) %>% 
    purrr::map2(c("Original", "MMUPHin adjusted"), function(phylo, Data) {
      ordination <- phyloseq::ordinate(phylo, method = "MDS", distance = "bray")
      list(cluster = plot_ordination(phylo, ordination = ordination, color = "cluster") +
             ggtitle(Data),
           batch = plot_ordination(phylo, ordination = ordination, color = "batch") +
             ggtitle(Data))
    })
  
  cowplot::plot_grid(plotlist = list(l_p[[1]]$cluster, l_p[[2]]$cluster,
                                     l_p[[1]]$batch, l_p[[2]]$batch), nrow = 2) %>% 
    ggsave(filename = paste0(dir_output, "example_ordination_", i, ".pdf"),
           .,
           width = 10, height = 8)
}
```
