---
title: "evaluate for discrete structure discovery"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
Evaluate for discrete structure discovery

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath("../"))
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup()
dir_output <- "results/discrete/"
dir.create(dir_output, recursive = TRUE, showWarnings = TRUE)
```

```{r load data}
# parallel computing
ncores <- 20
load(paste0(dir_output, "tb_sim.RData"))
```

```{r evaluate metrics before correction}
N <- nrow(tb_sim)
registerDoParallel(ncores)
results <- foreach(i = 1:N) %dopar% {
  cat(i, "\n", file = paste0(dir_output, "evaluate_before_progress.txt"), append = TRUE)
  mat_otu <- read.table(paste0(dir_output,
                               "sparseDOSSA_sets/",
                               i, ".tsv"),
                        header = TRUE,
                        sep = "\t",
                        row.names = 1) %>% 
    as.matrix
  i_simSetup <- tb_sim[i, ]
  df_metadata <- i_simSetup$df_metadata[[1]]

  phylo <- phyloseq::phyloseq(
    phyloseq::otu_table(mat_otu, taxa_are_rows = TRUE),
    sample_data(df_metadata)) %>%
    transform_sample_counts(MMUPHin:::tss) %>%
    prune_taxaSamples()
  D <- distance(phylo, method = "bray")
  R2_cluster <- vegan::adonis(D ~ cluster,
                              data = sample_data2(phylo),
                              permutations = 2)$aov.tab["cluster", "R2"]
  R2_batch <- vegan::adonis(D ~ batch,
                            data = sample_data2(phylo),
                            permutations = 2)$aov.tab["batch", "R2"]
  
  pred.str <-
    fpc::prediction.strength(
      xdata = D,
      Gmin = 2,
      Gmax = 10,
      clustermethod = fpc::claraCBI,
      classification = "centroid",
      M = 5,
      distances = TRUE,
      count = FALSE)$mean.pred[-1] %>%
    data.frame(k = 2:10, mean_pred = .)

  return(list(R2 = c("cluster" = R2_cluster,
                     "batch" = R2_batch), 
              pred.str = pred.str))
}
stopImplicitCluster()
save(results, file = paste0(dir_output, "evaluate_before.RData"))
```


```{r batch correction and evaluate metrics after correction}
rm(results)
registerDoParallel(ncores)
results_correct <- foreach(i = 1:N) %dopar% {
  cat(i, "\n", file = paste0(dir_output, "evaluate_after_progress.txt"), append = TRUE)
  mat_otu <- read.table(paste0(dir_output,
                               "sparseDOSSA_sets/",
                               i, ".tsv"),
                        header = TRUE,
                        sep = "\t",
                        row.names = 1) %>% 
    as.matrix
  i_simSetup <- tb_sim[i, ]
  df_metadata <- tb_sim[i, ]$df_metadata[[1]]
  
  mat_otu <- mat_otu %>% 
      MMUPHin::adjust.batch(batch = "batch", 
                            data = df_metadata,
                            diagnostics = FALSE, 
                            verbose = FALSE)
  
  phylo <- phyloseq::phyloseq(
    phyloseq::otu_table(mat_otu, taxa_are_rows = TRUE),
    sample_data(df_metadata)) %>%
    transform_sample_counts(MMUPHin:::tss) %>%
    prune_taxaSamples()
  D <- distance(phylo, method = "bray")
  R2_cluster <- vegan::adonis(D ~ cluster,
                              data = sample_data2(phylo),
                              permutations = 2)$aov.tab["cluster", "R2"]
  R2_batch <- vegan::adonis(D ~ batch,
                            data = sample_data2(phylo),
                            permutations = 2)$aov.tab["batch", "R2"]
  
  pred.str <-
    fpc::prediction.strength(
      xdata = D,
      Gmin = 2,
      Gmax = 10,
      clustermethod = fpc::claraCBI,
      classification = "centroid",
      M = 5,
      distances = TRUE,
      count = FALSE)$mean.pred[-1] %>%
    data.frame(k = 2:10, mean_pred = .)
  
  return(list(R2 = c("cluster" = R2_cluster,
                     "batch" = R2_batch), 
              pred.str = pred.str))
} 
stopImplicitCluster()
save(results_correct, file = paste0(dir_output, "evaluate_after.RData"))
```
