---
title: "sparseDOSSA simulation for lm.meta function"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
sparseDOSSA simulation for lm.meta function

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath("../"))
# setwd("simulation/")
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup()
dir_output <- "results/lm.meta/"
dir.create(dir_output, recursive = TRUE, showWarnings = TRUE)
```

```{r simulation parameters for continuous covariate}
# parallel computing
ncores <- 20
# sample size
nBatch <- c(5, 10)
nSample_perBatch <- c(50, 100)
# feature size
nMicrobe <- c(50, 300)
spikeMicrobes <- c(0.1, 0.2, 0.5)
# metadata specification
metadata_type <- c("batch" = "factor",
                   "exposure" = "numeric")
tb_effectSize <- tidyr::crossing(batch = c(0.1, 1, 2, 5),
                                 exposure = c(0.1, 1, 2, 5))
effectSize <- tibble::tibble(effectSize = 
                               (1:nrow(tb_effectSize)) %>% 
                               purrr::map(function(i) unlist(tb_effectSize[i, ])))
# replicates
rep <- 1:10
# metadata simulation
fDummyData <- TRUE
fDummyDirection <- TRUE
# additional setup
noZeroInflate <- FALSE

tb_simSetup <- tidyr::crossing(
  rep,
  nBatch,
  nSample_perBatch,
  nMicrobe,
  spikeMicrobes,
  noZeroInflate,
  effectSize
) %>% 
  dplyr::mutate(nSample = nBatch * nSample_perBatch)
```

```{r simulate continuous metadata}
set.seed(1)
tb_simCont <- tb_simSetup %>% 
  dplyr::group_by(1:n()) %>% 
  dplyr::mutate(df_metadata = list(
    data.frame(batch = rep(1:nBatch, each = nSample_perBatch) %>% 
                 as.factor(),
               exposure = rnorm(1:nSample),
               row.names = paste0("Sample", 1:nSample))),
    spikein.mt = list(create_spikein.mt(
      number_features = nMicrobe,
      percent_spiked = spikeMicrobes,
      effectSize = 
        create_effectSize(effectSize = effectSize[[1]],
                          df_metadata = df_metadata[[1]],
                          metadata_type = metadata_type,
                          fDummyData = fDummyData,
                          fDummyDirection = fDummyDirection),
      seed = rep))) %>% 
  dplyr::ungroup()
save(tb_simCont, file = paste0(dir_output, "tb_simCont.RData"))
N <- 10
```

```{r run sparseDOSSA continuous}
registerDoParallel(ncores)
l_sparseDOSSA <- foreach(i = 1:N) %dopar% {
  i_simSetup <- tb_simCont[i, ]
  
  otu_count <- sparseDOSSA::sparseDOSSA(
    number_features = i_simSetup$nMicrobe,
    number_samples = i_simSetup$nSample,
    UserMetadata = 
      create_metadataMatrix(df_metadata = i_simSetup$df_metadata[[1]],
                            metadata_type = metadata_type,
                            fDummyData = fDummyData,
                            fDummyDirection = fDummyDirection,
                            scale = FALSE),
    spikein.mt = i_simSetup$spikein.mt[[1]] %>% 
      dplyr::group_by(feature) %>% 
      dplyr::mutate(metadata = paste(metadata, collapse = ";"), 
                    strength = paste(strength, collapse = ";")) %>% 
      dplyr::slice(1) %>%  
      dplyr::ungroup(),
    noZeroInflate = i_simSetup$noZeroInflate,
    percent_spiked = i_simSetup$spikeMicrobes,
    seed = i_simSetup$rep,
    minLevelPercent = 0,
    write_table = FALSE,
    verbose = FALSE) %>%
    extract_sparseDOSSA() %>%
    extract2("features")
  
  return(otu_count)
}
stopImplicitCluster()
save(l_sparseDOSSA, file = paste0(dir_output, "sparseDOSSA_cont.RData"))
```

```{r simulation parameters for discrete covariate}
# metadata specification
# Exposure is still numeric because it's just two levels
metadata_type <- c("batch" = "factor",
                   "exposure" = "numeric")
```

```{r simulate discrete metadata}
set.seed(1)
tb_simDisc <- tb_simSetup %>% 
  dplyr::group_by(1:n()) %>% 
  dplyr::mutate(df_metadata = list(
    data.frame(batch = rep(1:nBatch, each = nSample_perBatch) %>% 
                 as.factor(),
               exposure = rbinom(n = nSample, size = 1, prob = 0.5) %>% 
                 as.numeric(),
               row.names = paste0("Sample", 1:nSample))),
    spikein.mt = list(create_spikein.mt(
      number_features = nMicrobe,
      percent_spiked = spikeMicrobes,
      effectSize = 
        create_effectSize(effectSize = effectSize[[1]],
                          df_metadata = df_metadata[[1]],
                          metadata_type = metadata_type,
                          fDummyData = fDummyData,
                          fDummyDirection = fDummyDirection),
      seed = rep))) %>% 
  dplyr::ungroup()
save(tb_simDisc, file = paste0(dir_output, "tb_simDisc.RData"))
N <- 10
```

```{r run sparseDOSSA discrete}
registerDoParallel(ncores)
l_sparseDOSSA <- foreach(i = 1:N) %dopar% {
  i_simSetup <- tb_simDisc[i, ]
  
  otu_count <- sparseDOSSA::sparseDOSSA(
    number_features = i_simSetup$nMicrobe,
    number_samples = i_simSetup$nSample,
    UserMetadata = 
      create_metadataMatrix(df_metadata = i_simSetup$df_metadata[[1]],
                            metadata_type = metadata_type,
                            fDummyData = fDummyData,
                            fDummyDirection = fDummyDirection,
                            scale = FALSE),
    spikein.mt = i_simSetup$spikein.mt[[1]] %>% 
      dplyr::group_by(feature) %>% 
      dplyr::mutate(metadata = paste(metadata, collapse = ";"), 
                    strength = paste(strength, collapse = ";")) %>% 
      dplyr::slice(1) %>%  
      dplyr::ungroup(),
    noZeroInflate = i_simSetup$noZeroInflate,
    percent_spiked = i_simSetup$spikeMicrobes,
    seed = i_simSetup$rep,
    minLevelPercent = 0,
    write_table = FALSE,
    verbose = FALSE) %>%
    extract_sparseDOSSA() %>%
    extract2("features")
  
  return(otu_count)
}
stopImplicitCluster()
save(l_sparseDOSSA, file = paste0(dir_output, "sparseDOSSA_disc.RData"))
```
