---
title: "Evaluation for lm.meta function"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
Evaluation for lm.meta function

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath("../"))
# setwd("simulation/")
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup()
dir_output <- "results/lm.meta/"
dir.create(dir_output, recursive = TRUE, showWarnings = TRUE)
```

```{r load data}
ncores <- 20

load(paste0(dir_output, "tb_sim.RData"))
```

```{r run meta-analysis before batch adjustment}
N <- nrow(tb_sim)
N <- 3
registerDoParallel(ncores)
results <- foreach(i = 1:N) %dopar% {
  cat(i, "\n", file = paste0(dir_output, "evaluate_before_progress.txt"), append = TRUE)
  mat_otu <- read.table(paste0(dir_output,
                               "sparseDOSSA_sets/",
                               i, ".tsv"),
                        header = TRUE,
                        sep = "\t",
                        row.names = 1) %>% 
    as.matrix
  i_simSetup <- tb_sim[i, ]
  df_metadata <- i_simSetup$df_metadata[[1]]
  
  phylo <- phyloseq::phyloseq(
    phyloseq::otu_table(mat_otu, taxa_are_rows = TRUE),
    sample_data(df_metadata)) %>%
    transform_sample_counts(MMUPHin:::tss) %>%
    prune_taxaSamples()
  D <- distance(phylo, method = "bray")
  R2_exposure <- vegan::adonis(D ~ exposure,
                              data = sample_data2(phylo),
                              permutations = 2)$aov.tab["exposure", "R2"]
  R2_batch <- vegan::adonis(D ~ batch,
                            data = sample_data2(phylo),
                            permutations = 2)$aov.tab["batch", "R2"]
  
  fit_lm.meta <- MMUPHin::lm.meta(feature.count = mat_otu,
                                  batch = "batch",
                                  exposure = "exposure",
                                  data = df_metadata,
                                  normalization = "TSS",
                                  transform = "AST",
                                  directory = paste0(dir_output, "MMUPHin_before/", i, "/"),
                                  forest.plots = FALSE,
                                  verbose = FALSE)
  fit_Maaslin2 <- MMUPHin:::Maaslin2.wrapper(
    feature.count = mat_otu,
    data = df_metadata,
    exposure = "exposure",
    directory = paste0(dir_output, "MMUPHin_before/", i, "/all/")
  )
  return(list(MMUPHin = fit_lm.meta$meta.results,
              naive = fit_Maaslin2,
              R2 = c("exposure" = R2_exposure,
                     "batch" = R2_batch)))
}
stopImplicitCluster()
save(results, file = paste0(dir_output, "evaluate_before.RData"))
```

```{r batch correction and run meta-analysis}
registerDoParallel(ncores)
results_correct <- foreach(i = 1:N) %dopar% {
  cat(i, "\n", file = paste0(dir_output, "evaluate_after_progress.txt"), append = TRUE)
  mat_otu <- read.table(paste0(dir_output,
                               "sparseDOSSA_sets/",
                               i, ".tsv"),
                        header = TRUE,
                        sep = "\t",
                        row.names = 1) %>% 
    as.matrix
  i_simSetup <- tb_sim[i, ]
  df_metadata <- i_simSetup$df_metadata[[1]]
  
  mat_otu <- mat_otu %>% 
      MMUPHin::adjust.batch(batch = "batch", 
                            data = df_metadata,
                            diagnostics = FALSE, 
                            verbose = FALSE)
  
  phylo <- phyloseq::phyloseq(
    phyloseq::otu_table(mat_otu, taxa_are_rows = TRUE),
    sample_data(df_metadata)) %>%
    transform_sample_counts(MMUPHin:::tss) %>%
    prune_taxaSamples()
  D <- distance(phylo, method = "bray")
  R2_exposure <- vegan::adonis(D ~ exposure,
                              data = sample_data2(phylo),
                              permutations = 2)$aov.tab["exposure", "R2"]
  R2_batch <- vegan::adonis(D ~ batch,
                            data = sample_data2(phylo),
                            permutations = 2)$aov.tab["batch", "R2"]
  
  fit_lm.meta <- MMUPHin::lm.meta(feature.count = mat_otu,
                                  batch = "batch",
                                  exposure = "exposure",
                                  data = df_metadata,
                                  normalization = "TSS",
                                  transform = "AST",
                                  directory = paste0(dir_output, "MMUPHin_after/", i, "/"),
                                  forest.plots = FALSE,
                                  verbose = FALSE)
  fit_Maaslin2 <- MMUPHin:::Maaslin2.wrapper(
    feature.count = mat_otu,
    data = df_metadata,
    exposure = "exposure",
    directory = paste0(dir_output, "MMUPHin_after/", i, "/all/")
  )
  return(list(MMUPHin = fit_lm.meta$meta.results,
              naive = fit_Maaslin2,
              R2 = c("exposure" = R2_exposure,
                     "batch" = R2_batch)))
}
stopImplicitCluster()
save(results_correct, file = paste0(dir_output, "evaluate_after.RData"))
```
