---
title: "Unit test for lm.meta function"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
Unit test for lm.meta function

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath("../"))
# setwd("simulation/")
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup()
dir_output <- "results/lm.meta/unit_test/"
dir.create(dir_output, recursive = TRUE, showWarnings = TRUE)
```

```{r simulation parameters for continuous covariate}
# parallel computing
ncores <- 6
# sample size
nBatch <- c(5)
nSample_perBatch <- c(50)
# feature size
nMicrobe <- c(50)
spikeMicrobes <- c(0.2)
# metadata specification
metadata_type <- c("batch" = "factor",
                   "exposure" = "numeric")
tb_effectSize <- tidyr::crossing(batch = c(0.1, 1, 2, 5),
                                 exposure = c(0.1, 1, 2, 5))
effectSize <- tibble::tibble(effectSize = 
                               (1:nrow(tb_effectSize)) %>% 
                               purrr::map(function(i) unlist(tb_effectSize[i, ])))
# replicates
rep <- 1:5
# metadata simulation
fDummyData <- TRUE
fDummyDirection <- TRUE
# additional setup
noZeroInflate <- FALSE

tb_simSetup <- tidyr::crossing(
  rep,
  nBatch,
  nSample_perBatch,
  nMicrobe,
  spikeMicrobes,
  noZeroInflate,
  effectSize
) %>% 
  dplyr::mutate(nSample = nBatch * nSample_perBatch)
```

```{r simulate continuous metadata}
set.seed(1)
tb_simCont <- tb_simSetup %>% 
  dplyr::group_by(1:n()) %>% 
  dplyr::mutate(df_metadata = list(
    data.frame(batch = rep(1:nBatch, each = nSample_perBatch) %>% 
                 as.factor(),
               exposure = rnorm(1:nSample),
               row.names = paste0("Sample", 1:nSample))),
    spikein.mt = list(create_spikein.mt(
      number_features = nMicrobe,
      percent_spiked = spikeMicrobes,
      effectSize = 
        create_effectSize(effectSize = effectSize[[1]],
                          df_metadata = df_metadata[[1]],
                          metadata_type = metadata_type,
                          fDummyData = fDummyData,
                          fDummyDirection = fDummyDirection),
      seed = rep))) %>% 
  dplyr::ungroup()
save(tb_simCont, file = paste0(dir_output, "tb_simCont.RData"))
N <- nrow(tb_simCont)
```

```{r run sparseDOSSA continuous}
registerDoParallel(ncores)
l_sparseDOSSA <- foreach(i = 1:N) %dopar% {
  i_simSetup <- tb_simCont[i, ]
  
  otu_count <- sparseDOSSA::sparseDOSSA(
    number_features = i_simSetup$nMicrobe,
    number_samples = i_simSetup$nSample,
    UserMetadata = 
      create_metadataMatrix(df_metadata = i_simSetup$df_metadata[[1]],
                            metadata_type = metadata_type,
                            fDummyData = fDummyData,
                            fDummyDirection = fDummyDirection,
                            scale = FALSE),
    spikein.mt = i_simSetup$spikein.mt[[1]] %>% 
      dplyr::group_by(feature) %>% 
      dplyr::mutate(metadata = paste(metadata, collapse = ";"), 
                    strength = paste(strength, collapse = ";")) %>% 
      dplyr::slice(1) %>%  
      dplyr::ungroup(),
    noZeroInflate = i_simSetup$noZeroInflate,
    percent_spiked = i_simSetup$spikeMicrobes,
    seed = i_simSetup$rep,
    minLevelPercent = 0,
    write_table = FALSE,
    verbose = FALSE) %>%
    extract_sparseDOSSA() %>%
    extract2("features")
  
  return(otu_count)
}
stopImplicitCluster()
save(l_sparseDOSSA, file = paste0(dir_output, "sparseDOSSA_cont.RData"))
```

```{r simulation parameters for discrete covariate}
# metadata specification
# Exposure is still numeric because it's just two levels
metadata_type <- c("batch" = "factor",
                   "exposure" = "numeric")
```

```{r simulate discrete metadata}
set.seed(1)
tb_simDisc <- tb_simSetup %>% 
  dplyr::group_by(1:n()) %>% 
  dplyr::mutate(df_metadata = list(
    data.frame(batch = rep(1:nBatch, each = nSample_perBatch) %>% 
                 as.factor(),
               exposure = rbinom(n = nSample, size = 1, prob = 0.5) %>% 
                 as.numeric(),
               row.names = paste0("Sample", 1:nSample))),
    spikein.mt = list(create_spikein.mt(
      number_features = nMicrobe,
      percent_spiked = spikeMicrobes,
      effectSize = 
        create_effectSize(effectSize = effectSize[[1]],
                          df_metadata = df_metadata[[1]],
                          metadata_type = metadata_type,
                          fDummyData = fDummyData,
                          fDummyDirection = fDummyDirection),
      seed = rep))) %>% 
  dplyr::ungroup()
save(tb_simDisc, file = paste0(dir_output, "tb_simDisc.RData"))
```

```{r run sparseDOSSA discrete}
registerDoParallel(ncores)
l_sparseDOSSA <- foreach(i = 1:N) %dopar% {
  i_simSetup <- tb_simDisc[i, ]
  
  otu_count <- sparseDOSSA::sparseDOSSA(
    number_features = i_simSetup$nMicrobe,
    number_samples = i_simSetup$nSample,
    UserMetadata = 
      create_metadataMatrix(df_metadata = i_simSetup$df_metadata[[1]],
                            metadata_type = metadata_type,
                            fDummyData = fDummyData,
                            fDummyDirection = fDummyDirection,
                            scale = FALSE),
    spikein.mt = i_simSetup$spikein.mt[[1]] %>% 
      dplyr::group_by(feature) %>% 
      dplyr::mutate(metadata = paste(metadata, collapse = ";"), 
                    strength = paste(strength, collapse = ";")) %>% 
      dplyr::slice(1) %>%  
      dplyr::ungroup(),
    noZeroInflate = i_simSetup$noZeroInflate,
    percent_spiked = i_simSetup$spikeMicrobes,
    seed = i_simSetup$rep,
    minLevelPercent = 0,
    write_table = FALSE,
    verbose = FALSE) %>%
    extract_sparseDOSSA() %>%
    extract2("features")
  
  return(otu_count)
}
stopImplicitCluster()
save(l_sparseDOSSA, file = paste0(dir_output, "sparseDOSSA_disc.RData"))
```

```{r load data}
load(paste0(dir_output, "tb_simCont.RData"))
load(paste0(dir_output, "tb_simDisc.RData"))
load(paste0(dir_output, "sparseDOSSA_cont.RData"))
l_sparseDOSSA_cont <- l_sparseDOSSA
load(paste0(dir_output, "sparseDOSSA_disc.RData"))
l_sparseDOSSA_disc <- l_sparseDOSSA

l_tb_results <- list(
  cont = tb_simCont %>% 
    dplyr::mutate(otu_count = l_sparseDOSSA_cont,
                  success = sapply(otu_count, class) == "matrix"),
  disc = tb_simDisc %>% 
    dplyr::mutate(otu_count = l_sparseDOSSA_disc,
                  success = sapply(otu_count, class) == "matrix")
)

l_tb_results %>% 
  purrr::map_dbl(function(tb_results) mean(tb_results$success))
# View(tb_results %>% dplyr::filter(!success))
# i_simSetup <- tb_results %>% dplyr::filter(!success) %>% dplyr::slice(1)
l_tb_results <- l_tb_results %>% 
  purrr::map(function(tb_results) {
    tb_results %>% dplyr::filter(success)
  })
# Total number iterations. Set so easy to have testing run
N <- l_tb_results %>% purrr::map_dbl(nrow)
```

```{r run meta-analysis before batch adjustment}
for(metadata_type in c("cont", "disc")){
  registerDoParallel(ncores)
  tb_results <- l_tb_results[[metadata_type]]
  l_lm.meta_before <- foreach(i = 1:N[metadata_type]) %dopar% {
    i_result <- tb_results[i, ]
    fit_lm.meta <- MMUPHin::lm.meta(feature.count = i_result$otu_count[[1]],
                                    batch = "batch",
                                    exposure = "exposure",
                                    data = i_result$df_metadata[[1]],
                                    normalization = "TSS",
                                    transform = "AST",
                                    directory = paste0(dir_output, "MMUPHin/"),
                                    forest.plots = TRUE,
                                    verbose = FALSE)
    return(fit_lm.meta$meta.results)
  }
  stopImplicitCluster()
  save(l_lm.meta_before, 
       file = paste0(dir_output, 
                     "lm.meta_", 
                     metadata_type,
                     "_before.RData"))
}
```

```{r batch adjustment}
for(metadata_type in c("cont", "disc")){
  registerDoParallel(ncores)
  tb_results <- l_tb_results[[metadata_type]]
  l_adjust.batch <- foreach(i = 1:N[metadata_type]) %dopar% {
    i_result <- tb_results[i, ]
    otu_adjust <- MMUPHin::adjust.batch(
      feature.count = i_result$otu_count[[1]],
      batch = "batch",
      covariates = c("exposure"),
      data = i_result$df_metadata[[1]],
      zero.inflation = TRUE,
      pseudo.count = 0.5,
      diagnostics = FALSE,
      verbose = FALSE
    )
    return(otu_adjust)
  }
  stopImplicitCluster()
  save(l_adjust.batch, file = paste0(dir_output, "adjust.batch_",
                                     metadata_type, ".RData"))
}
```

```{r run meta-analysis after batch adjustment}
for(metadata_type in c("cont", "disc")){
  registerDoParallel(ncores)
  tb_results <- l_tb_results[[metadata_type]]
  load(paste0(dir_output, "adjust.batch_", metadata_type, ".RData"))
  l_lm.meta_after <- foreach(i = 1:N[metadata_type]) %dopar% {
    i_result <- tb_results[i, ]
    fit_lm.meta <- MMUPHin::lm.meta(feature.count = l_adjust.batch[[i]],
                                    batch = "batch",
                                    exposure = "exposure",
                                    data = i_result$df_metadata[[1]],
                                    normalization = "TSS",
                                    transform = "AST",
                                    directory = paste0(dir_output, "MMUPHin/"),
                                    forest.plots = TRUE,
                                    verbose = FALSE)
    return(fit_lm.meta$meta.results)
  }
  stopImplicitCluster()
  save(l_lm.meta_after, 
       file = paste0(dir_output, 
                     "lm.meta_", 
                     metadata_type,
                     "_after.RData"))
}
```

```{r load data for summary}
load(paste0(dir_output, "tb_simCont.RData"))
load(paste0(dir_output, "tb_simDisc.RData"))
l_tb_sim <- list(
  cont = tb_simCont,
  disc = tb_simDisc
)

ll_lm.meta_before <- list()
load(paste0(dir_output, "lm.meta_disc_before.RData"))
ll_lm.meta_before[["disc"]] <- l_lm.meta_before
load(paste0(dir_output, "lm.meta_cont_before.RData"))
ll_lm.meta_before[["cont"]] <- l_lm.meta_before

ll_lm.meta_after <- list()
load(paste0(dir_output, "lm.meta_disc_after.RData"))
ll_lm.meta_after[["disc"]] <- l_lm.meta_after
load(paste0(dir_output, "lm.meta_cont_after.RData"))
ll_lm.meta_after[["cont"]] <- l_lm.meta_after
```

```{r summarise results and plot}
for(metadata_type in c("cont", "disc")) {
  tb_results <- list(ll_lm.meta_before[[metadata_type]], 
                     ll_lm.meta_after[[metadata_type]]) %>% 
    purrr::map2_dfr(c("before", "after"),
                    function(l_results, data) 
                    {l_results %>% 
                        purrr::imap_dfr(
                          function(results, i) 
                          {results %>% 
                              dplyr::mutate(i = i)}) %>% 
                        dplyr::mutate(data = data)})
  tb_results <- tb_results %>% 
    dplyr::left_join(l_tb_sim[[metadata_type]] %>% dplyr::mutate(i = 1:n()),
                     by = "i")
  tb_results <- tb_results %>% 
    dplyr::mutate(features_TP = purrr::map2(spikein.mt, nBatch, 
                                            function(i_df_spikein, i_nBatch)
                                              i_df_spikein %>% 
                                              dplyr::filter(metadata == i_nBatch * 2 - 1) %>% 
                                              dplyr::pull(feature) %>% 
                                              paste0("Feature", .)),
                  TP = purrr::map2_lgl(feature, features_TP, function(i_feature, i_features_TP)
                    i_feature %in% i_features_TP))
  tb_summarise <- tb_results %>% 
    dplyr::group_by(i, data) %>% 
    dplyr::summarise(power = sum(TP & pval < 0.05, na.rm = TRUE) / sum(TP),
                     FPR = sum(!TP & pval < 0.05, na.rm = TRUE) / sum(!TP)) %>% 
    dplyr::ungroup()
  tb_summarise <- tb_summarise %>% 
    dplyr::left_join(l_tb_sim[[metadata_type]] %>% dplyr::mutate(i = 1:n()),
                     by = "i") 
  p_power <- tb_summarise %>% 
    dplyr::arrange(nBatch, nSample_perBatch) %>% 
    dplyr::mutate(nBatch_nSample_perBatch = 
                    paste0("nBatch=", nBatch, ";",
                           "nSample_perBatch=", nSample_perBatch) %>% 
                    factor %>% forcats::fct_inorder()) %>% 
    dplyr::arrange(nMicrobe, spikeMicrobes) %>% 
    dplyr::mutate(nMicrobe_percMicrobe = 
                    paste0("nMicrobe=", nMicrobe, ";",
                           "percSpike=", spikeMicrobes) %>% 
                    factor %>% forcats::fct_inorder()) %>% 
    dplyr::mutate(effect_batch = effectSize %>% 
                    purrr::map_dbl("batch"), 
                  effect_exposure = effectSize %>% 
                    purrr::map_dbl("exposure")) %>% 
    dplyr::arrange(effect_exposure) %>% 
    dplyr::mutate(effect_exposure = effect_exposure %>% factor %>% forcats::fct_inorder()) %>%
    dplyr::arrange(desc(effect_batch)) %>% 
    dplyr::mutate(effect_batch = effect_batch %>% factor %>% forcats::fct_inorder()) %>%
    dplyr::mutate(data = factor(data, levels = c("before", "after"))) %>% 
    ggplot(aes(x = effect_batch,
               y = power,
               alpha = data,
               fill = effect_exposure)) +
    geom_boxplot() +
    facet_grid(nBatch_nSample_perBatch ~ nMicrobe_percMicrobe, scales = "free_y")
  p_FPR <- tb_summarise %>% 
    dplyr::arrange(nBatch, nSample_perBatch) %>% 
    dplyr::mutate(nBatch_nSample_perBatch = 
                    paste0("nBatch=", nBatch, ";",
                           "nSample_perBatch=", nSample_perBatch) %>% 
                    factor %>% forcats::fct_inorder()) %>% 
    dplyr::arrange(nMicrobe, spikeMicrobes) %>% 
    dplyr::mutate(nMicrobe_percMicrobe = 
                    paste0("nMicrobe=", nMicrobe, ";",
                           "percSpike=", spikeMicrobes) %>% 
                    factor %>% forcats::fct_inorder()) %>% 
    dplyr::mutate(effect_batch = effectSize %>% 
                    purrr::map_dbl("batch"), 
                  effect_exposure = effectSize %>% 
                    purrr::map_dbl("exposure")) %>% 
    dplyr::arrange(effect_exposure) %>% 
    dplyr::mutate(effect_exposure = effect_exposure %>% factor %>% forcats::fct_inorder()) %>%
    dplyr::arrange(desc(effect_batch)) %>% 
    dplyr::mutate(effect_batch = effect_batch %>% factor %>% forcats::fct_inorder()) %>%
    dplyr::mutate(data = factor(data, levels = c("before", "after"))) %>% 
    ggplot(aes(x = effect_batch,
               y = FPR,
               alpha = data,
               fill = effect_exposure)) +
    geom_boxplot() +
    facet_grid(nBatch_nSample_perBatch ~ nMicrobe_percMicrobe, scales = "free_y")
}
```




