---
title: "Generate subset figures for unsupervised validation"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
Generate subset figures for unsupervised validation

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath("../"))
# setwd("simulation/")
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup()
dir_output <- "results/unsupervised_subset/"
dir.create(dir_output, recursive = TRUE, showWarnings = TRUE)
```

```{r discrete validation}
dir_results <- "results/discrete/"
load(paste0(dir_results, "tb_sim.RData"))
tb_sim <- tb_sim %>% 
  dplyr::mutate(effect_cluster = effectSize %>% 
                  purrr::map_dbl("cluster"),
                effect_batch = effectSize %>% 
                  purrr::map_dbl("batch"),
                i = 1:n()) %>% 
  dplyr::select(-`1:n()`)
load(paste0(dir_results, "evaluate_before.RData"))
load(paste0(dir_results, "evaluate_after.RData"))

tb_predStr <- list(results, results_correct) %>% 
  purrr::map2_dfr(names(colors_simulation_unsupervised), 
                  ~ .x %>% 
                    purrr::imap_dfr(function(result, i) {
                      nCluster_true <- tb_sim[i, ]$nCluster
                      tb_result <- result$pred.str
                      tb_result %>% 
                        dplyr::arrange(-(k == nCluster_true),
                                       -mean_pred) %>% 
                        dplyr::slice(1:2) %>% 
                        dplyr::arrange(-mean_pred) %>% 
                        dplyr::mutate(pred_str_rank = c("highest", "second"),
                                      i = i)
                    }) %>% 
                    data.frame(Data = .y)) %>% 
  dplyr::mutate(Data = factor(Data, levels = names(colors_simulation_unsupervised)))

p_success <- tb_predStr %>% 
  dplyr::filter(pred_str_rank == "highest") %>% 
  dplyr::left_join(tb_sim, by = "i") %>% 
  dplyr::filter(nSample == 1000, nBatch == 2) %>%
  dplyr::filter(!(effect_batch == 0 & Data == "MMUPHin corrected")) %>% 
  dplyr::filter(effect_cluster == 10) %>% 
  dplyr::mutate(success = (k == nCluster)) %>% 
  dplyr::group_by(effect_batch,
                  nCluster, nBatch,
                  nMicrobe, Data) %>% 
  dplyr::summarise(mean_success = mean(success)) %>% 
  ggplot(aes(x = as.factor(effect_batch), y = mean_success, 
             color = Data)) +
  geom_point(position = position_dodge(width = 0.5), size = 3) +
  facet_grid(.~paste0("nCluster=", nCluster)) +
  scale_color_manual(values = colors_simulation_unsupervised) +
  xlab("Batch effect size") + ylab("% successfully identify right number of clusters")
ggsave(filename = paste0(dir_output, "discrete.pdf"), p_success, 
       width = 15, height = 4)
```

```{r continuous validation}
dir_results <- "results/continuous/"
load(paste0(dir_results, "tb_sim.RData"))
tb_sim <- tb_sim %>% 
  dplyr::mutate(effect_score = effectSize %>% 
                  purrr::map_dbl("score"),
                effect_batch = effectSize %>% 
                  purrr::map_dbl("batch"),
                effect_score_plot = paste0("effect score=", effect_score) %>% 
                   factor(levels = paste0("effect score=", c(1, 5, 10))),
                i = 1:n()) %>% 
  dplyr::select(-`1:n()`)
load(paste0(dir_results, "evaluate_before.RData"))
load(paste0(dir_results, "evaluate_after.RData"))

tb_continuous <- list(results, results_correct) %>% 
  purrr::map2_dfr(names(colors_simulation_unsupervised), 
                  ~ .x %>% 
                    purrr::imap_dfr(~ data.frame(cor_cutoff = .x$fit.continuous$cor.cutoff,
                                                 correlation = .x$fit.continuous$correlation,
                                                 i = .y)) %>% 
                    data.frame(Data = .y)) %>% 
  dplyr::mutate(Data = factor(Data, levels = names(colors_simulation_unsupervised)))
p_correlation <- tb_continuous %>% 
  dplyr::left_join(tb_sim, by = "i") %>% 
  dplyr::filter(nSample == 1000, effect_score == 10, nBatch == 4) %>%
  dplyr::filter(!(effect_batch == 0 & Data == "MMUPHin corrected")) %>% 
  ggplot(aes(x = as.factor(effect_batch), y = abs(correlation), 
             color = Data)) +
  geom_boxplot() +
  scale_color_manual(values = colors_simulation_unsupervised) +
  xlab("Batch effect size") + ylab("correlation(true score, identified score)")
ggsave(filename = paste0(dir_output, "continuous.pdf"), p_correlation, 
       width = 8, height = 4)
```
